### ISSUE TITLE
Create Workflow Tasks

### ISSUE THREAD

**Issue by JoelWiebe** [encorelab/ck-board#123]
The teacher can create Workflow Tasks by clicking on the Workflow Tools icon in the top application navigation bar. 

Workflow Tasks define the tasks sent to the CK Workspace tool for each student or group.

Example 1
From board/bucket: _Equitable Design_
Operation: _Distribute_
Criteria: _Randomly_
At least _5_ posts per student

Assign to: _Each student_
Student prompt: _Please use tags to categorize each idea (e.g., financial, transportation, technology)_

Required: _tag_

![image](https://user-images.githubusercontent.com/6416247/147900216-f00d447c-99ca-4e88-89ad-50c5d54f8843.png)

**Example 2**
From board/bucket: _Sorted Bucket_
Operation: _Distribute_
Criteria: By _tag_ - _Transportation_

Assign to: _Transportation group_
Student prompt: _Please review your peers' ideas and upvote promising ideas._

Permissions: _Comment; upvote_

**Comment by Ammar-T** [comment]
Completed.
