### ISSUE TITLE
Create CK Workspace Tool

### ISSUE THREAD

**Issue by JoelWiebe** [encorelab/ck-board#124]
Students have a CK Workspace that will be accessed exclusively on their mobile devices. This interface receives the tasks assigned by teacher through the Workflow tools.

The interface displays a list of assigned tasks, allows students to open and view those tasks, and for students to generate content (e.g., votes, comments, tags, or new posts).

![image](https://user-images.githubusercontent.com/6416247/146953692-f75f10dd-c199-4b8e-ac3e-f00f469ed9df.png)

**Comment by Ammar-T** [comment]
Completed.
