### ISSUE TITLE
CK Workspace for Groups

### ISSUE THREAD

**Issue by JoelWiebe** [encorelab/ck-board#125]
If a Workflow Task is assigned to a group, all group members can see the full list of items assigned (i.e., the Transportation group gets all notes tagged with as Transportation).

The posts may exist as a queue whereby each time students request to work on an assigned post they get the first item from the queue, that is removed from the queue. If they complete work on the post it is marked as completed. If they decide to put that post back, it is added back to the end of the queue. This will ensure that only one student has any given post open at a given time.

The number of completed posts are denoted in the Workspace.

**Comment by Ammar-T** [comment]
Completed.
