### ISSUE TITLE
Workspace Progress Bars

### ISSUE THREAD

**Issue by JoelWiebe** [encorelab/ck-board#126]
If working individually, each student can see their progress in a progress bar (i.e., completed tagging 0/5 posts). Another colour could represent the average number of posts completed across all students in the class. Perhaps some kind of a legend, labels, or tooltip could help differentiate. 

![image](https://user-images.githubusercontent.com/6416247/147111705-187e9e90-36db-4a53-86fd-ecc6e7181864.png)

For groups, each student in a group can see a progress bar in the workspace that shows their progress. In this case, the other colour could represent the average number of posts completed across all students in the _group_.

**Comment by Ammar-T** [comment]
Completed.
