### ISSUE TITLE
Nest boards within projects

### ISSUE THREAD

**Issue by JoelWiebe** [encorelab/ck-board#128]
In the main dashboard, add projects as the top-level that contain boards

For teachers:

- Projects created or subscribed to by the teacher are shown under “My Projects”
- Therefore the teacher will have both join and add icons available
- When creating a board, teachers have the option to select which project it belongs to

For students:

- As students cannot create projects or boards, only projects subscribed to by students are shown under My Projects
- Therefore students will have only the join icon available 

NOTE: Join codes will now operate on a per-project-level rather than on a board level

![image](https://user-images.githubusercontent.com/6416247/148121306-7d68d84c-4b90-4389-893a-e829e32a0ae8.png)

Teachers can create new projects from the main dashboard
![image](https://user-images.githubusercontent.com/6416247/149850568-5592d6e4-c06c-478e-9f35-7ce661b77a01.png)

**Comment by l3n0ire** [comment]
@JoelWiebe Will there be an option to assign existing boards to a project? Also do boards have to be nested under a project or can they exist on their own?

**Comment by JoelWiebe** [comment]
@l3n0ire Great question! I was thinking that every board must be contained within a project. In this case, we would need to migrate existing boards to some project(s) just for these legacy boards then all future boards would be inside projects.

@Ammar-T what do you think?

P.S. Another thing to think about, I was also considering moving join codes for Membership to the Project level. This would make sense for most scenarios as one or more boards are often intended for a team or class of students. Perhaps, in the future, we may consider giving groups access to different boards within a project but for now I would be fine with all students having access to all boards within a project.

**Comment by Ammar-T** [comment]
@JoelWiebe I'm wondering if it's worth migrating existing boards to projects because I'm not sure if people are actually using our boards yet? Most of the ones I've seen have just been created for testing purposes 😄. Although, if I'm wrong, then yes we definitely need to add these boards to projects.

Also, +1 on moving join codes to the project level.

**Comment by JoelWiebe** [comment]
@Ammar-T Thanks for the quick feedback -- and good point! There is just one board that may be of interest, "Use Cases for CK Board" but if it's much work then maybe I'll just take a close read over a few posts before wiping out all the existing boards! Let me know :)

**Comment by Ammar-T** [comment]
@JoelWiebe @l3n0ire If it's just that one board then Colin can manually update Firebase to add it to a project. As for the rest of the boards, they can be deleted.

**Comment by JoelWiebe** [comment]
@l3n0ire @Ammar-T 
Here's what I was trying to show regarding project to board navigation (and we can use the "back arrow" to navigate from boards back to the projects page)
![image](https://user-images.githubusercontent.com/6416247/150182619-38bcc803-9867-4306-af96-c357a28fd8cb.png)

![image](https://user-images.githubusercontent.com/6416247/150182682-6552f91a-1377-4b65-9e06-dad8b8bd3405.png)

I think it might be okay for teachers to have to navigate into a project to create a board (since teachers would often only be generating content for one project at a time, but if there are cases where you think creating boards from the projects page makes life easier, I am happy with that too)!

**Comment by l3n0ire** [comment]
I was thinking have having one add button where they teacher change choose to either create a board or a project. That way they don't have to navigate to the correct project
![image](https://user-images.githubusercontent.com/22690560/150423914-e2b10751-33b6-49aa-97fd-b1abb9dd16b5.png)

On the board creation menu they can choose which project the board belongs to.
![image](https://user-images.githubusercontent.com/22690560/150423994-585bef1a-b5c5-48ed-b5c9-963f4b009852.png)

**Comment by Ammar-T** [comment]
@l3n0ire Great idea! I'm on board to do it that way if Joel agrees.

This could also potentially help in the future if we ever decide to distribute a board to multiple projects. Although, this is pretty off-topic 😄.

**Comment by JoelWiebe** [comment]
@l3n0ire @Ammar-T That looks pretty clean.

What were you thinking if someone has already navigated inside a project, would they still need to specify whether to create a new board or new project? Also, if creating a new board from within a project would they still need to then specify which project to place the board in? 

Whichever will be simpler in the long run works for me!

**Comment by Ammar-T** [comment]
We could add some logic to remove the "Add Project" option when the user is in the project dashboard. 

If the user's in a project already and wants to create a board, we can set the assigned project in the modal to default to the current project perhaps. Although, feel free to implement it however you like best @l3n0ire 😄.

Side note: this made me think about having projects within projects 🤔. Wonder if this could be a useful use-case in the future @JoelWiebe ?

**Comment by l3n0ire** [comment]
I implemented what @Ammar-T  suggested
![image](https://user-images.githubusercontent.com/22690560/150648544-9a71d7bc-e134-43bd-a73d-f28961c41b57.png)
![image](https://user-images.githubusercontent.com/22690560/150648476-91a1cbab-e2b0-4b91-987c-042cf3afa753.png)

@JoelWiebe Would this issue include project configuration like managing members, project name, isPublic etc or should we make that a separate issues?

**Comment by JoelWiebe** [comment]
@Ammar-T Thanks for advancing the conversation! I think having only one level of projects should be good for now, although Jim did remind me of one nuance within SCORE. SCORE has a project, but the project can have multiple "periods" (one for each class) whereby each period would get its own copy of the designed activities. For CK Board this would mean that each period would have its own student list and its own copy of the created boards (or at least not be able to see posts from students in other periods). Although I'm tempted to not worry about any of this at this point and just get everything working for a single period at this point. Maybe we can brainstorm about this sometime along with Colin?

@StevenWuzz Great work. That sounds like a good solution. Let's keep the tabs Board, Task, Permissions, and Tags at the Board level and move Members to the Project level. That would mean that at the Project level we would have the tabs Project (with name change), Members (same as was implemented at the board level), and in the future Groups for management of student groups.

For the time being, let's drop the notion of Public projects or boards as this opens up a bunch of nuances in terms of who is a member and which teachers have permission to edit, etc.
