### ISSUE TITLE
Add posts directly to a bucket

### ISSUE THREAD

**Issue by JoelWiebe** [encorelab/ck-board#142]
Allow users to create posts from the bucket view. These would not show up in the board until a user explicitly moves them to the board. 

We can move posts either (1) individually from a bucket to its parent board (i.e., either manually dragged to a point on the screen or dropped in the centre of the board) or (2) all posts from a _particular_ bucket to a parent board all at once (perhaps randomly or clustered around the centre of the canvas) (Covered by #150)

We should also have some means of identifying whether a post in a bucket is already on its parent board (perhaps by icon).

**Comment by l3n0ire** [comment]
I'll create a separate issue for moving posts from bucket to board. I was thinking of allow users to select which posts to move to the board (checkbox). Once the user has made all their selections, they can click a move to board button. Would be simpler to implement compared to drag and drop.
