### ISSUE TITLE
Add `onDestroy` lifecycle method to close listeners

### ISSUE THREAD

**Issue by Ammar-T** [encorelab/ck-board#149]
Currently, for some components we are not unsubscribing from listeners after the component has been destroyed. For example, in `canvas.component.ts` we setup tons of listeners for mouse, keyboard, database changes. However, we never close these listeners.

To solve this, add the `onDestroy` lifecycle method which will be responsible for closing all listeners before the component is completely destroyed. Do this for all listeners in all components.

To see an example, you can check this out: https://github.com/encorelab/ck-board/blob/d27d9291876ed9ac1b81ecb70ec70cd7d06a0638/src/app/components/html-post/html-post.component.ts#L129-L132

**Comment by JoelWiebe** [comment]
Thanks!
