### ISSUE TITLE
Require student to drag the note to the desired location on note creation

### ISSUE THREAD

**Issue by Ammar-T** [encorelab/ck-board#15]
When a new note is created, it shouldn't just be placed on the canvas at a specific location automatically. 

Instead, the user should be able to drag the note on creation and place it at their desired location.

**Comment by JoelWiebe** [comment]
This could actually be achieved by reversing the steps (i.e., clicking before writing the note). (1) Click a button for creating a new note (cursor changes to one for placing an object), (2) click where you want to place the note (note dialogue pops up), edit the note contents and save (note is created at clicked location).

Perhaps, if we have a toolbar on canvas, one button can be for creating a new note (another could be for changing drag/move mode, etc.)
