### ISSUE TITLE
Background images broken

### ISSUE THREAD

**Issue by JoelWiebe** [encorelab/ck-board#164]
Uploaded images often do not show completely. Perhaps there is an issue with the size of the image. 

Should we change our approach to compress and store the picture on the server rather than store the image as text as I believe we have done?

**Comment by l3n0ire** [comment]
The images not showing completely was a scaling error which I have fixed. However the background images are unable to be uploaded to firebase. My guess is that the images are too large to be stored as a string. @Ammar-T @JoelWiebe  I was thinking of uploading the images directly to firebase then saving the link to that image in the board. Fabric can set background images from urls. I'm not sure what the storage and read/write limits with firebase storage are.

**Comment by JoelWiebe** [comment]
@l3n0ire Thanks for making quick work of this. Yes, looks like uploading looks like the way to go. Is it better to store the image in Firebase or should we store the file in an "assets" folder on the server then the server holds the URL to the uploaded asset. Also, I believe that Angular has a client side image compression feature that we can use to get all images down to the KB range rather than multiple MB per image... we use this in SCORE.

**Comment by JoelWiebe** [comment]
I believe this shows the image compression implementation (at the bottom) -- also the storing of files in a directory: https://github.com/WISE-Community/WISE-DEPRECATED/pull/2395/files
