### ISSUE TITLE
Reduce the sensitivity of pinch gesture for canvas zoom

### ISSUE THREAD

**Issue by JoelWiebe** [encorelab/ck-board#170]
On laptop trackpads, the pinch gesture is very sensitive. Can we slightly reduce the trackpad pinch-zoom gesture?

**Comment by JoelWiebe** [comment]
@StevenWuzz I found the hard-coded value! Would you mind updating the pinch-zoom value from 0.95 to 0.99? Feel free to merge without review.

**Comment by StevenWuzz** [comment]
@JoelWiebe I've just fixed it directly in the develop branch!
