### ISSUE TITLE
Move back button to left side?

### ISSUE THREAD

**Issue by JoelWiebe** [encorelab/ck-board#186]
The back button is somewhat hidden among other tools in the nav bar. Should we move the back button to the left side of the navigation bar or just below on the left side and change the icon to a conventional larger back arrow?

**Comment by breity** [comment]
Yes, I think moving to the left of the nav bar or top of the content makes sense.

I'm also looking to add navigation breadcrumbs to the top of the main content, as we discussed a bit in our last meeting. Maybe this would negate the need for the back button in the dashboard and project views? Board view could also show the breadcrumbs at the top or have a close button maybe

What do you think?

**Comment by Ammar-T** [comment]
Being handled by #195
