### ISSUE TITLE
Export posts to csv

### ISSUE THREAD

**Issue by Ammar-T** [encorelab/ck-board#19]
For research, we need to be able to log user events (i.e., moving posts, tagging, commenting, etc.) and export this data as a CSV file including the post, comment, and tag contents so that researchers can analyze student work and activities.

SCORE has a similar export feature. Perhaps we can discuss this in more detail.

**Comment by JoelWiebe** [comment]
@StevenWuzz This would be an important feature that you would be very welcome to work on!
