### ISSUE TITLE
Fix snackbar CSS/design

### ISSUE THREAD

**Issue by Ammar-T** [encorelab/ck-board#210]
Update the snackbar component to complement the new CK-Board theme. 

Choose valid colours, font-sizes, etc. to match the new theme.

**Comment by JoelWiebe** [comment]
@breity Would you be able to take a look at this? Our snackbars are invisible :)

If you click the view task button at the top...
![image](https://user-images.githubusercontent.com/6416247/159591657-7d7e4a0c-ada5-4a4b-98b5-cc5f2ac0a0c0.png)

... then a snackbar should persist across the bottom of the canvas:
![image](https://user-images.githubusercontent.com/6416247/159591783-f20992d5-10ac-477c-a42f-fe705b1370d9.png)

However, the text is white and the snackbar no longer has a background colour. Would you be able to add a background colour to the snackbar and select an appropriate colour for the text?
