### ISSUE TITLE
Add User Post Subscriptions and Notifications

### ISSUE THREAD

**Issue by JoelWiebe** [encorelab/ck-board#213]
Create Board Notifications tool for receiving notifications, for instance, upon:
- Comment, upvote, or tag by another user to their posts

Board Notifications could include a Bell icon in the top navigation bar with a numerical counter indicating the number of notifications. Once clicked, a tray could be displayed that shows a list of notifications. Selecting a notification could open the modal pop-up for that post. 

SCORE has something like this:
<img width="314" alt="Screen Shot 2022-03-22 at 9 07 22 PM" src="https://user-images.githubusercontent.com/6416247/159601941-ce78016d-ae3d-463f-9b45-61cff8c04af7.png">

**Comment by Ammar-T** [comment]
@JoelWiebe Should we first create some way of receiving notifications? For example, a toolbar button that opens a drawer of notifications on the canvas page?

**Comment by JoelWiebe** [comment]
@Ammar-T Yes, that would be great, perhaps a bell icon with a counter of the number of notifications. Clicking the bell could expand down to a list of posts that were updated. Clicking on the notification could open the modal for that post (and maybe pan to that post as well?).

SCORE has something like this:
<img width="314" alt="Screen Shot 2022-03-22 at 9 07 22 PM" src="https://user-images.githubusercontent.com/6416247/159601941-ce78016d-ae3d-463f-9b45-61cff8c04af7.png">

**Comment by JoelWiebe** [comment]
@Ammar-T, just a heads up, I assigned this one to @l3n0ire

**Comment by l3n0ire** [comment]
@Ammar-T I made a sequence diagram for the notification system. lmk what you think
https://drive.google.com/file/d/1Fe1h5d4ukpLqrRmCA_OI9FPigupn5PlB/view?usp=sharing
