### ISSUE TITLE
Add Hyperlinks to Snackbar

### ISSUE THREAD

**Issue by JoelWiebe** [encorelab/ck-board#218]
How hard would it be to customize the View Task Snackbar so that it parses the task description for URLs and converts them to hyperlinks?

E.g., Task Description: Please review the website example.com/fakenews. What is the evidence for or against this article? Post your responses on the canvas above.

(Clicking on example.com/fakenews would open that URL in a new browser tab; development of this may be able to combine our existing URL parser with a custom SnackBar - https://stackoverflow.com/questions/46949233/insert-a-link-into-matsnackbar)

**Comment by JoelWiebe** [comment]
@StevenWuzz @l3n0ire @Ammar-T Would any of you have time to do this by Thursday? If this is possible, we can look for a workaround. Let me know!

**Comment by Ammar-T** [comment]
@JoelWiebe #220
