### ISSUE TITLE
Num likes and comments is incorrect

### ISSUE THREAD

**Issue by JoelWiebe** [encorelab/ck-board#243]
The number of likes and comments displayed on the canvas does not necessarily match the number in the modal post pop-up. 

For example: project/1647961013141-YxXrM7L8g4WHlgvlmn81hrTtbEy1/board/1648228593348-YxXrM7L8g4WHlgvlmn81hrTtbEy1

![image](https://user-images.githubusercontent.com/6416247/160490033-95b07f13-f9aa-42b7-a9d1-e2d305dda441.png)

If you work on this, I can provide the join code for your convenience :)

**Comment by JoelWiebe** [comment]
@Ammar-T do we know yet what might have caused the multiple listeners?

**Comment by Ammar-T** [comment]
@JoelWiebe I haven't had much time to look into it yet so I'm not exactly sure what it could've been.
