### ISSUE TITLE
Delete Comment

### ISSUE THREAD

**Issue by JoelWiebe** [encorelab/ck-board#244]
Allow students to edit or delete their own comments; prevent students from editing or deleting others' notes. Allow teachers to delete anyone's comment.

"Deleted" comments should remain stored in the database, but tagged as deleted and hidden in its post

The delete "filled trash" icon may be presented in the top right corner of the comment (as displayed today), preferably, only on mouse hover of that comment (if relatively easy to implement). Tentatively, we can also display a confirmation dialogue (e.g., "Are you sure you want to delete this comment?") -- perhaps this dialogue could be removed in the future if we have some means of users recovering deleted comments.

<img width="312" alt="Screen Shot 2022-05-26 at 1 08 42 AM" src="https://user-images.githubusercontent.com/6416247/170420163-3e5ff296-5ad4-45c2-b84a-ca3801db6cce.png">

**Comment by JoelWiebe** [comment]
@zarifmahmud What do you think about us only focusing on deleting comments and not worrying about editing for the time being?

**Comment by JoelWiebe** [comment]
I've updated the description above to only delete comments (leave editing out for the time being) and add a dialogue box. A screenshot is provided above and also here: https://docs.google.com/presentation/d/1HCbXmwMkj3ZgOKnBdI348iymSdOGt4a3/edit#slide=id.g12d3605ddae_0_5

**Comment by zarifmahmud** [comment]
Yep I'm not currently working on it! It can be re-assigned

**Comment by zarifmahmud** [comment]
Just added the permission functionality, I think it should actually be good to go now
