### ISSUE TITLE
Delete buckets

### ISSUE THREAD

**Issue by JoelWiebe** [encorelab/ck-board#251]
Allow for the deletion of buckets. This might be possible by changing the Create Bucket tab under the Workflows tool to a Manage Buckets tab that includes options for deleting buckets.

**Comment by LunarFang416** [comment]
@JoelWiebe for displaying the boards in the manage boards tab, do we want to display all boards (like below) and delete them from there, or do we want a drop down?

<img width="703" alt="Screen Shot 2022-06-28 at 1 37 52 PM" src="https://user-images.githubusercontent.com/73078183/176247243-46eb47de-3a8a-41fd-b076-6d91d8b4e8a4.png">

**Comment by JoelWiebe** [comment]
@LunarFang416 Great questions! 

1. When we delete the buckets, let's keep the posts 
2. For the UI, let's move Create Bucket to the top (most used, most accessible) and move the create button beside (or below) the bucket name field; if the number of buckets are overwhelming we could hide the Delete Buckets section and only show that if the user clicks on a delete buckets button (at which point the delete button disappears and the delete buckets section appears) -- but we could make this latter part a future issue
<img width="578" alt="Screen Shot 2022-06-29 at 12 23 27 AM" src="https://user-images.githubusercontent.com/6416247/176351184-cda0950b-0a41-4725-9fad-01ff5e4f91db.png">
 
What do you think?

**Comment by JoelWiebe** [comment]
@LunarFang416 Sounds great! Thanks
