### ISSUE TITLE
Bug: Users Notified of their own actions

### ISSUE THREAD

**Issue by l3n0ire** [encorelab/ck-board#261]
Users should not receive notifications when they comment on, tag or like their own post.  We should check if the notification recipient is the same user as the one who triggered the notification and prevent the system from sending the notification.

Potential Solution:
Add a check in canvas.service.ts for userIDs

**Comment by Ammar-T** [comment]
I would suggest not taking this on until the websocket stuff is integrated. It'll be much easier to send notifications to users connected (and exclude the sender as well!).

**Comment by Ammar-T** [comment]
Added in #260.
