### ISSUE TITLE
Groupings - UI - Initial Reasoning

### ISSUE THREAD

**Issue by Ammar-T** [encorelab/ck-board#270]
Building on top of #269, we also need to create a UI for creating groups, updating groups (i.e. renaming group, adding/removing users from group), deleting groups, presenting a user's list of groups.

~~Firstly, we'll have to figure out how groups will be associated. Will groups be specific to each project? Should groups be a global entity where they can be visible to many different projects (tricky)? Should groups be specific per board (probably not)? @JoelWiebe Feel free to join the discussion on this as well.~~

**For now, let's make groups relative to a project since all users can only join projects.**

Next, where should we add the ability to create groups? Should we create a "Create Group" modal similar to what we have for boards and projects, where they click the "+" icon and then "Create Group"? 

How do we access groups? Should there be a whole separate page for users to view all the groups they're in? This is where they could also update or leave those groups as well.

On the canvas page, how can teacher see all the groups within that board? Should this be through the settings modal or should we create a separate modal for users to see the groups for that board?

Those are just some questions we should think about before actually writing up a UI since there's a lot of ways we can do this. Feel free to do mockups or just have a general explanation of how groups should work from a UI perspective.

**Comment by JoelWiebe** [comment]
@Ammar-T Sorry I missed this! Great questions.

I'll also add @zarifmahmud @DCH25 to keep them in the loop.

To match how SCORE handles this, we should probably have groups organized at the project level (also for reasons you point out). Therefore, we could consider adding the grouping UI in the project settings pop-up (as seen below)
<img width="435" alt="Screen Shot 2022-06-13 at 1 23 47 PM" src="https://user-images.githubusercontent.com/6416247/173409998-010050b3-9e4c-4c50-8783-4df6ffc9ef88.png">

As groupings will be relevant to the CK Workspace, there should be some way of showing students' work group assignment to them when they are working on a group task (and the ability to view the list of their group members in some detailed group view). At this point, we may not need students to see all groups or group members, but to only see their own group for a particular group task they have open should be sufficient.
<img width="422" alt="Screen Shot 2022-06-13 at 1 41 17 PM" src="https://user-images.githubusercontent.com/6416247/173412618-d45c38d2-aa60-45fa-b9e0-773b6ce49254.png">

Also, we currently do not have any group self-assignment for students, but maybe down the road we can think about this.
