### ISSUE TITLE
Groupings - UI - Implementation

### ISSUE THREAD

**Issue by Ammar-T** [encorelab/ck-board#271]
Once we answer the questions in #270 and know what we're building, we can start to implement the UI!

This issue will be highly dependant on what's decided from #270, so we can scope this out a little later. @DCH25 We can also split this up into smaller issues later on in case it's a lot of UI work.

**Comment by JoelWiebe** [comment]
Any updates? Feel free to send me a direct message in Slack if I'm missing conversations here. I'm happy to support discussions to keep us moving quickly on these!
