### ISSUE TITLE
CK Workspace - General UI

### ISSUE THREAD

**Issue by Ammar-T** [encorelab/ck-board#276]
Create a new page for the CK Workspace which users can access from the canvas page.

Layout should include all active, inactive task workflows as a list while also being able to view buckets, board list view, and all groups in that workspace.

**Comment by JoelWiebe** [comment]
I'm still playing with the mockups: https://docs.google.com/presentation/d/1HCbXmwMkj3ZgOKnBdI348iymSdOGt4a3/edit#slide=id.g10b5d63c7a7_1_5 

Please let me know when I can review what we have so far :)

**Comment by Ammar-T** [comment]
Completed.
