### ISSUE TITLE
CK Workspace - Tasks Functionality - API (Still needs to be fleshed out fully)

### ISSUE THREAD

**Issue by Ammar-T** [encorelab/ck-board#278]
Similar to how we have `runDistributionWorkflow()` inside `workflow.agent.ts`, we need to create a function for running task workflows as well. This function should be responsible for the following:

- Distribute x number of posts from `source` to **each** assigned group. 
- If there are no assigned groups (i.e. `assignedGroups == []`), then distribute x posts to each person associated with that board (everyone).

But before we actually implement that algorithm, we have to figure out how we'll map assigned posts to each group. 

We should create a new model mapping "group" to "assigned posts" for a task workflow, it'll essentially store the progress for a group for a specific task workflow:
```
class GroupTask {
  id: string // unique id

  workflowID: string // the associated task workflow 

  members: string[] // ids of all group members for this task
  posts: {
    postID: string; // id of post
    memberID: string; // which member of group is assigned to complete this post (i.e. maybe tag it, or whatever the task may be)
    actions: TaskActions[] // tracking progress for each post
  }[]
}
```

**Comment by zarifmahmud** [comment]
I added a GroupTask model based on this schema on the task_workflow2 branch
