### ISSUE TITLE
Add BUCKET_REMOVE_POST event type to CK trace logs

### ISSUE THREAD

**Issue by JoelWiebe** [encorelab/ck-board#280]
There is currently a BUCKET_ADD_POST, but no event type and no logs for BUCKET_REMOVE_POST. Can we add this event type and record logs where posts are removed from buckets?

**Comment by l3n0ire** [comment]
@JoelWiebe Should we have new variables names for this event. (ex postRemovedFromBucketID) or reuse the existing ones for BUCKET_ADD_POST

**Comment by JoelWiebe** [comment]
@l3n0ire Sorry, I missed this. Yes, looks like you added the new variable. I'll test now.
