### ISSUE TITLE
Replace "likes" with dot-voting ("upvotes")

### ISSUE THREAD

**Issue by JoelWiebe** [encorelab/ck-board#287]
I'm thinking about replacing upvotes with dot-voting/sticker-voting (from design thinking). Rather than having students "like" a post because it does something for them emotionally, students could each have a set number of dots (e.g., 5) to upvote the best idea on a board. A single post could receive no vote, one vote, or multiple votes -- but the student only as a set number of votes (e.g. 5) that they can use on an entire board.

**Comment by Ammar-T** [comment]
@JoelWiebe I was scrolling through Reddit and remembered our conversation about downvotes 🤣. 

Maybe we could add downvotes but keep the amount hidden from students but visible to teachers?

**Comment by JoelWiebe** [comment]
Haha, nice :) 

What do you think about a toggle option? Either Option 1, sticker-voting with an authored limit of upvotes per board where a post could receive multiple sticker-upvotes (and no downvotes) OR Option 2, common voting (with up- and down-voting) where each post could receive either an upvote or a downvote (for this option there is no need to author a limit of votes as each post in the board can receive an upvote or a downvote). I suppose this would require two different backends but only one front end. The values and input limits would change based on the selected voting option. How doable would that be? Could we start with one implementation then add the other later?

**Comment by Ammar-T** [comment]
I think starting with option 1 is the way to go! When you say a post could receive multiple sticker-upvotes, does that mean one person can upvote a single post multiple times using up more than 1 given upvote? For example, if Bob get 3 upvotes, can he use all of them on one post? @JoelWiebe

**Comment by Ammar-T** [comment]
Another question: Should the upvote limit only happen for posts on the canvas or should it also apply to posts inside a bucket (bucket-only posts)?

**Comment by JoelWiebe** [comment]
@Ammar-T Great questions!

Yes, if Bob gets a max of three upvotes in the OISE Finances board, then all three could be spent on a single post. We might want some way of indicating not only the total sum of all upvotes but also whether Bob has given a post one, two, or more upvotes and the total number of remaining upvotes to spend on the board. Maybe I'll play around with a few mockups for your feedback.

To answer your second question, good edge case. I would say that the upvote limit would also apply to bucket-only posts as all buckets and boards are essentially within the same board scope, they are merely posts with and without a location.

**Comment by Ammar-T** [comment]
@JoelWiebe Makes sense!

For displaying the number of upvotes per post, after users click on the number inside the post modal we could open up a list of all users who've upvoted it and how many times as well. Similar to what Instagram and Facebook do except we'll have a number besides each user indicating how many upvotes.

For displaying how many likes remain per user, I was thinking we could add this inside the full task modal. Let me know how all of this sounds to you 😄.

**Comment by Ammar-T** [comment]
This also means we should probably prioritize filtering inside list view as students may want to see all the posts they've upvoted in case they want to undo votes to use them somewhere else.

**Comment by JoelWiebe** [comment]
That list view of upvotes is a neat idea. Do you think there could be a way for us to indicate on a canvas card or list view card whether they have upvoted a post. This could be as simple as enabling a downvote icon once they have upvoted to show that they can remove their upvote for that post. (Maybe you've done this already).

In terms of showing the remaining upvotes. This should probably be something that could be consistently displayed across the canvas, list view, and workspace view. I think it would be nice if this was always visible and not hidden inside a modal. Or maybe each time they vote, the snack bar displays the remaining number of upvotes after each vote. That might be the easiest/best way to manage this.

**Comment by Ammar-T** [comment]
Currently what I have is distinct colors on the upvote icon when it's upvoted (purple) or not upvoted (black). But after learning that one user could have multiple upvotes we would need to add a downvote icon as well since we can't just toggle whether they've upvoted a post now.

For displaying upvotes we could keep it visible on the bottom left of the canvas. I like that better than keeping it hidden in a modal, good point!

**Comment by JoelWiebe** [comment]
Perfect! :)
