### ISSUE TITLE
Fix Remaining Upvotes

### ISSUE THREAD

**Issue by JoelWiebe** [encorelab/ck-board#300]
1) When the number of upvotes is increased in the board configurations, the remaining upvotes indicator is successfully updated. However, when the number of upvotes is decreased in the board configurations the number of remaining upvotes is NOT decreased (allowing the number of remaining to get out of synch)->
<img width="762" alt="Screen Shot 2022-06-28 at 2 33 06 PM" src="https://user-images.githubusercontent.com/6416247/176256917-a2ccd035-a1a5-461b-a54c-8f26390ca772.png">

2) Could we also make a wording change in the snackbar notification, from "You have already surpassed the upvote limit" to "You have reached the upvote limit"

<img width="865" alt="Screen Shot 2022-06-28 at 2 36 20 PM" src="https://user-images.githubusercontent.com/6416247/176257395-89ee00a0-b8c1-4d38-954c-4c5b80b4c1a7.png">

**Comment by zarifmahmud** [comment]
What should be done if the number of upvotes is decreased, but a student had already reached the old max? Should their most recent upvotes be removed?
