### ISSUE TITLE
Change dot-voting icons

### ISSUE THREAD

**Issue by JoelWiebe** [encorelab/ck-board#306]
Can we change the dot-voting icons in the canvas, buckets, and post editors from arrows to upward/downward triangles? E.g.,
- (https://emojipedia.org/upwards-button/)
- https://fonts.google.com/icons?selected=Material+Symbols+Outlined:arrow_drop_up:FILL@0;wght@400;GRAD@0;opsz@48 

Also, on the canvas and buckets can we swap the comment icon and dot-voting icon (so that comment is on the left and dot-voting is on the right)?

**Comment by LunarFang416** [comment]
@JoelWiebe how do these look?
<img width="312" alt="Screen Shot 2022-07-04 at 1 12 22 PM" src="https://user-images.githubusercontent.com/73078183/177196993-e6828fed-7bc6-4427-9f7d-5f330e450686.png">

**Comment by JoelWiebe** [comment]
Those arrows look perfect! :) Should we also swap the votes and the comments icon (put upvotes on the right and comments on the left), what do you think?

**Comment by LunarFang416** [comment]
I have no preference over either way, but if we want to swap their positions I think we should do it for every post regardless if it is on the board, canvas or list.

**Comment by JoelWiebe** [comment]
Agreed. Let's leave the location swap alone for now then and just do the icons. 

Thanks for you work on this!

**Comment by zarifmahmud** [comment]
My bad! I had this page open yesterday, and it hadn't updated that @LunarFang416 was already working on this
