### ISSUE TITLE
Create TODO List

### ISSUE THREAD

**Issue by JoelWiebe** [encorelab/ck-board#338]
- A Personal TODO List can be added to the Task Workspace UI
- There is one Personal TODO List per project
- Each student creates their own personal TODO list items

A TODO list item is typically about something to be completed outside of CK (e.g., ask tutor a question, talk to teacher about test prep, make study notes, etc.). Each TODO list item contains two elements:
- name
- deadline (date and time)

A TODO item is completed by simply clicking the corresponding checkbox. When the item is completed, a confetti animation is displayed with celebratory sound as reward/celebration. 

If the item is not yet completed as the deadline approaches, each student will receive a reminder of their approaching TODO item using the CK notifications tool (i.e., the student receives a notification the day before and on the day that it is due)

Once this feature is implemented, we can think about or explore ways of keeping track of completed items (maybe using trace logs for post study research analysis and UI such as timeline/graph visualizations for students to self-reflect on their progress in realtime)

**Comment by LunarFang416** [comment]
@JoelWiebe Quick question regarding sending notifications to users. If a user creates a task that has a due date within a few hours (less that 24 hours), when do we want to send a notification in that case? Or do we not send it at all?

**Comment by JoelWiebe** [comment]
Hey @LunarFang416, good question. Let's add one more notification, for missed deadlines (i.e., "Deadline missed for task: ..."). That would mean they would get a notification (1) the day before, (2) the day of, and (3) if they missed the time of the deadline.

The teacher may have further ideas about when to remind students, but to get started I think this is a pretty good way to start. Once we get the PR I'll see if I can review it with her.
