### ISSUE TITLE
Add "Question Authoring" Boards

### ISSUE THREAD

**Issue by JoelWiebe** [encorelab/ck-board#343]
### Overview
On board creation, allow teachers to select either "brainstorm" or "question authoring" boards. If question authoring board is selected, all post elements are preserved (e.g., title, comments, tags, upvotes, but the message is now either an open response question prompt or a multiple choice editor. A selector in the Add Post editor can choose whether the post is an open response prompt or a multiple choice question. Both are saved as JSON objects in SCORE authoring format. 

### Toggle “Brainstorm/Question Authoring” Board Type

**Figure 1. Add New Board Configurations**
<img width="349" alt="Screen Shot 2022-08-28 at 3 23 39 PM" src="https://user-images.githubusercontent.com/6416247/187091030-3ec02d5c-6728-4cf8-8520-628f4df0996e.png"> 

- In new board configurations, create the heading: Board Type
- Under the board type heading add toggle buttons: “Brainstorm” and “Question Authoring”

### Display Multiple Choice UI by Default for New Post Editor

When a new post is being created in a question authoring board, create a toggle button between "multiple choice" and "open response" 

<img width="405" alt="Screen Shot 2022-08-28 at 3 32 27 PM" src="https://user-images.githubusercontent.com/6416247/187091362-d2e24aed-4adf-45bf-8858-ffbb997a3a7c.png">

All the posts are either:

- Multiple Choice or Open Response
- When users select the question type, the UI will be updated to match selection
- Multiple Choice can be the default option 
- (We can port over SCORE’s multiple choice editor UI, advanced features such as image uploads, etc. can be removed)
- The Multiple Choice question prompt and choices will be saved as JSON as per the SCORE format 
- In the future, the JSON will be imported to SCORE as a question

### Display Open Response Posts when Enabled for New Post Editor

<img width="405" alt="Screen Shot 2022-08-28 at 3 35 06 PM" src="https://user-images.githubusercontent.com/6416247/187091443-b8ddd919-6e35-44db-85d2-4a7079b8590f.png">
When open response is selected, we may use the classic message box, however:

- The prompt instead of saying “Message” will say something else, such as “Open response question prompt”
- The authored open response prompt will be saved as JSON as per the SCORE format
- Again, in the future, the JSON will be imported to SCORE as a question

### Next step - Add MathJax/ASCIIMath Previewer for Multiple Choice and Open Response
<img width="446" alt="Screen Shot 2022-08-28 at 3 57 42 PM" src="https://user-images.githubusercontent.com/6416247/187092230-f44dcedf-b1a9-4f59-95c9-6bcd31f469b9.png">
---
<img width="441" alt="Screen Shot 2022-08-28 at 4 00 30 PM" src="https://user-images.githubusercontent.com/6416247/187092301-e39b2086-3ace-419a-b5c2-79f7d0f5134b.png">

**Comment by LunarFang416** [comment]
@JoelWiebe Once a board is created as a "Question authoring" type board, can itbe switched back to brainstorming? Or does the board stay as it is once created?

**Comment by JoelWiebe** [comment]
@LunarFang416 For simplicity, I was thinking that board types would be permanent, set on creation and never change. I think this makes more sense in terms of assigning tasks to students and later importing posts to SCORE if the board type stays the same and the post types are consistently either brainstorm posts or questions. Does that sound okay to you?

**Comment by JoelWiebe** [comment]
@LunarFang416 If you'd like to make some simplifications, feel free to do any of the below:

- Don't worry about getting the underlying JSON to match SCORE just yet (as I will just be reading and manually creating these in SCORE for now anyway)
- The Open Response can be our default message field but with a text prompt such as "Add open response question prompt"
- Multiple choice UI can be of your own design
- Multiple choice can be made to have only a single correct answer rather than have the option for multiple correct answers (as displayed in the SCORE multiple choice UI) 
- We can fix the number of choices for multiple choice to be four rather than dynamically generate any number of choices
- Also don't worry about adding MathJax while authoring posts in the first version, if we have time then great but otherwise it's okay if we do not

Hopefully this will make this feature more attainable within the current timeframe.

**Comment by JoelWiebe** [comment]
Hey @LunarFang416! How is this feature coming along? Would you mind creating a PR so I can test the work-in-progress when you get a chance?
