### ISSUE TITLE
Add "Create" log on post creation from buckets

### ISSUE THREAD

**Issue by JoelWiebe** [encorelab/ck-board#353]
The creation of a post from a bucket view should trigger a trace log of both "creating" and "adding" a post to this bucket. 

On creation of a post from a bucket view, a BUCKET_ADD_POST event is logged in trace logs. This is good, but we are missing the additional POST_CREATE event that includes the postModifiedTitle and postModifiedMessage values

**Comment by JoelWiebe** [comment]
Hey @Ammar-T! Would this be a relatively quick item to complete? 

P.S. Also, just curious, does the task workflow trigger trace logs?

**Comment by DCH25** [comment]
@JoelWiebe moving posts to a bucket with task workflows doesn't trigger the trace logs.

**Comment by JoelWiebe** [comment]
@DCH25 Good catch. For task workflows the action (e.g., creating post, tagging, upvoting, etc.) should trigger a trace log that references the student, but as moving the post from the source to the destination is an automated process, we should probably tag this as being moved by a task workflow. I'll do some thinking about this and add it as another lower priority issue -- thanks for pointing this out.
