### ISSUE TITLE
Refreshing browser on board causes blank page

### ISSUE THREAD

**Issue by JoelWiebe** [encorelab/ck-board#360]
On the staging server (e.g., http://ck-board-staging.herokuapp.com/project/a8443a29-635e-433a-a36b-90fdc845ad52) refreshing the browser on a board causes the board to become blank. I'm not sure whether this is a result of a SSO redirect or something else. 

This might be a staging server issue. If this works on production once we update, then all good. But I'll keep this as a reminder until we can test on production.

**Comment by Ammar-T** [comment]
@JoelWiebe This doesn't seem to be an issue on production for me. Can you check to confirm and then close this issue? Thanks!

**Comment by JoelWiebe** [comment]
@Ammar-T Yep, refreshing board pages works fine on production!
