### ISSUE TITLE
Create Lock Project Membership Toggle

### ISSUE THREAD

**Issue by JoelWiebe** [encorelab/ck-board#361]
As SSO (for the time being) removes board access restrictions, can we create a slide toggle in the Membership tab of the Project Configurations? Perhaps this toggle can be added just above the Invite Code.
<img width="331" alt="Screen Shot 2022-09-04 at 12 21 23 AM" src="https://user-images.githubusercontent.com/6416247/188297271-4d5f33e6-7cf9-4030-9950-02cd1a1a722a.png">

**Comment by JoelWiebe** [comment]
Hey @Ammar-T, is this still something we could figure out for Monday or Tuesday?

**Comment by Ammar-T** [comment]
@JoelWiebe I don't quite understand what's being asked for this issue. What would the the toggle be doing if enabled? Would it disable anyone from joining the project?

**Comment by JoelWiebe** [comment]
@Ammar-T Sorry for this vague description. 

Yes, it would essentially be a "lock membership" toggle. When enabled, no one can join this project (even if they have the invite codes or are using SCORE SSO) -- they cannot join. This is for security reasons, now that SCORE SSO opened up a big security hole because anyone logged into SCORE can open up any project. I essentially want students to join using SCORE SSO, then we turn on this lock so that no one else can access (membership will be closed). When the lock is turned off, students can join either using invite codes or SCORE SSO (this is the default that we now have). 

If lock membership is on then no one can join, even if they

**Comment by Ammar-T** [comment]
Thanks for the clarification, very nicely explained!

This can definitely be done by Monday, I'll start on this now.

**Comment by JoelWiebe** [comment]
@Ammar-T Cool, thanks!!
