### ISSUE TITLE
Tag Modifications Do Not Work

### ISSUE THREAD

**Issue by JoelWiebe** [encorelab/ck-board#398]
Modifications to tags are not working consistently. On one occasion, when I made changes to tags then clicked the Update Configurations button the tag deletions and additions did not persist, once board configurations were closed and the browser was refreshed, the deleted tags re-appear and the new tags disappear. However, on another occasion this worked just fine.

Can we have tags added to the database immediately when the Add Tag button is pressed and delete tags immediately when the x is clicked to delete a tag (i.e., no waiting until the "Update Configurations" button is pressed)

**Comment by Ammar-T** [comment]
Yeah that's fine, @JoelWiebe.

@LunarFang416 feel free to take this on.
