### ISSUE TITLE
Disable deletion of Needs Attention tag

### ISSUE THREAD

**Issue by JoelWiebe** [encorelab/ck-board#410]
In board configurations (as seen below), disable the ability to delete the Needs Attention tag so that students always have access to this tag. This could be achieved by simply removing the x next to Needs Attention tag in the board configurations.
<img width="678" alt="Screen Shot 2022-11-17 at 1 55 32 PM" src="https://user-images.githubusercontent.com/6416247/202533873-bef97b63-6258-4e22-bb10-2ec090d5d213.png">

**Comment by LunarFang416** [comment]
@JoelWiebe We are basically trying to make it a default tag for all boards? Or once the "Needs Attention" tag has been added to the board once, it can't be removed?

**Comment by JoelWiebe** [comment]
@LunarFang416 Sorry for the lack of clarity.

There are currently three default tags automatically added to each new board: Needs Attention, Idea, and Question. Needs Attention is a unique tag that also puts a red circle any post that uses this post. 

Teachers can edit the available tags in the board configurations. This means they can remove the Idea, Question, and Needs Attention tags. The problem is that if the Needs Attention tag is deleted, users can never get back the feature of accenting existing posts, so we want to disable the ability to delete the "Needs Attention" default tag. 

It is okay though if teachers delete the other default tags (Idea and Question).

Does this answer your question?
