### ISSUE TITLE
Enabling Viewing Submitted Posts in CK Workspace

### ISSUE THREAD

**Issue by JoelWiebe** [encorelab/ck-board#448]
Can we add toggle buttons in the CK workspace to toggle between viewing "All Posts" and "Pending Posts"?

I.e., Left aligned with the posts:
<img width="386" alt="Screen Shot 2022-12-20 at 9 04 14 PM" src="https://user-images.githubusercontent.com/6416247/208803262-98e2700d-9e48-42b8-bf2b-e0bdfad53e5b.png">

1. Pending Posts is selected by default
2. When Pending Posts is selected, submitted posts are hidden
3. When All Posts are selected, both submitted posts and pending posts are shown

**Comment by LunarFang416** [comment]
Marking this as closed since "View Draft/View Submitted" toggle added in #535
