### ISSUE TITLE
Collapse All CK Monitor Tasks

### ISSUE THREAD

**Issue by JoelWiebe** [encorelab/ck-board#449]
Tasks are currently expanded by default in the CK Monitor that can be cognitively overloading and make it difficult to quickly access the TODO monitor tools at the bottom of the pane.
<img width="424" alt="Screen Shot 2022-12-21 at 11 22 27 AM" src="https://user-images.githubusercontent.com/6416247/208954011-36c253e6-d7e4-4fe9-ace3-07f00f1c69ee.png">

Can we collapse all tasks by default?
<img width="283" alt="Screen Shot 2022-12-21 at 11 23 54 AM" src="https://user-images.githubusercontent.com/6416247/208954335-ae28e3c4-2139-458c-9fc4-3aefb301185f.png">

**Comment by DCH25** [comment]
Fixed in 5f1fac89cd8f9a251cb37745ea92792729e6784b
