### ISSUE TITLE
Cancel or Reopen Active Tasks

### ISSUE THREAD

**Issue by JoelWiebe** [encorelab/ck-board#467]
1. In the CK Monitor, create a Cancel option for unfinished tasks
<img width="143" alt="Screen Shot 2022-12-31 at 3 52 38 PM" src="https://user-images.githubusercontent.com/6416247/210155444-e8c8d89e-efbc-47b3-80b4-ad4d5abc67e8.png">

- [x] For active tasks, create an "Action" column on the far right of each row for tasks
- [x] For active tasks, add a "Cancel" icon to each row
- [x] For the Cancel icon, add the tooltip "Cancel task"
- [x] When the button is pressed, move the task from the Active Tasks list to the Completed Tasks list

2. In the CK Monitor, create a Play icon to send tasks back to Active tasks
<img width="144" alt="Screen Shot 2022-12-31 at 3 53 27 PM" src="https://user-images.githubusercontent.com/6416247/210155455-b331dca9-23e8-496b-aec0-a3e6aa4d27d4.png">

- [x] For completed tasks, create an "Action" column on the far right of each row for tasks
- [x] For completed tasks, add a "Play Circle" icon to each row
- [x] For the Play Circle icon, add the tooltip "Re-activate task"
- [x] When the button is pressed, move the task from the Completed Tasks list to the Active Tasks list

**Comment by JoelWiebe** [comment]
@LunarFang416 Would you be able to work on this one?

**Comment by LunarFang416** [comment]
@JoelWiebe For active tasks, when the complete task is selected, the progress should change from whatever it currently is to 100% (e.g. from 50% to 100% when clicked). And when the re-activate task is selected for completed tasks, its progress should go down to 0%? 
This would also cause the group tasks to also go to complete/active as well.

Is this how you want it to function?

**Comment by JoelWiebe** [comment]
@LunarFang416 Thanks for sending me this question!

I just want to make sure I understand your question. By selecting "complete task", do you mean selecting "Cancel task"?

In the description I wrote above, everything is being controlled from the CK Monitor. The case in which the above feature would be used is when there is no longer time to work on the activity and some students have not finished the task... however, we cannot just leave this task as active (we need to archive it to make room for new incoming tasks). Therefore, I suggest moving the task to Completed (as they are done with it for now). If, however, the teacher in the future wants them to return to working on this task, the teacher may reactivity that task for them so they can pick up where they left off and finish the last few items.  

Therefore, ideally the percentage does not change at all. For example, a task could be 50% done in Active Tasks and the teacher cancels the task. The Task would be moved to the Completed Tasks but still show 50%. When the teacher clicks re-activate the task would be moved back to Active Tasks and once again remain at 50%. Does this make sense? What do you think about this?

**Comment by JoelWiebe** [comment]
This feature is very helpful, thanks for all your work on this! Most of this works great, I just noticed a couple small things. 

Suggestions:
1. Table padding

- [ ] Can we add cell padding in the table? For instance, I notice that the "Progress" and "Action" headings can become pressed closely to one another (see image below)

<img width="1437" alt="Screen Shot 2023-01-31 at 2 02 15 PM" src="https://user-images.githubusercontent.com/6416247/215869866-d93e05b0-4b44-46a7-857f-604cb8bb862f.png">

2. Console logs

- [ ] Can we remove the table logs in the console, probably from testing (see image below)

<img width="1122" alt="Screen Shot 2023-01-31 at 2 10 50 PM" src="https://user-images.githubusercontent.com/6416247/215871654-eac4ec03-f592-40e0-9070-b52c59d3a3fb.png">

3. There is a bug when a task is assigned to multiple groups and some are still Pending while others are Active, e.g.:

 - Let's say there is a task called "Multi-assign 2" that has three groups and all three are in the Pending state -- so far so good
<img width="1433" alt="Screen Shot 2023-01-31 at 2 16 50 PM" src="https://user-images.githubusercontent.com/6416247/215872789-9f00194e-fe6d-4070-ac3b-565604695289.png">

 - Next, let's say that Group 1 starts the task and it becomes Active
 - Although the task is now appropriately displayed in the Active list for Group 1, Group 2 and 3 are no longer displayed in the Pending list

- [ ] Can we ensure that Group 2 and 3 would still be displayed in the Pending list?
<img width="1438" alt="Screen Shot 2023-01-31 at 2 19 29 PM" src="https://user-images.githubusercontent.com/6416247/215873465-b0c71219-8d2e-4d40-b7bc-b1fb8c5670c4.png">

 - Next, if the group 1 task is cancelled, it is successfully displayed in the Completed list but a blank Group list is displayed in the Active list

- [ ] Can we have Group 1 and Group 2 still remain displayed in the Pending list and have the task removed from the Active list in this instance?
<img width="1437" alt="Screen Shot 2023-01-31 at 2 21 12 PM" src="https://user-images.githubusercontent.com/6416247/215873807-038f874f-fa1f-4af0-9d9d-8843e2716ad6.png">
