### ISSUE TITLE
Pinch Zoom

### ISSUE THREAD

**Issue by JoelWiebe** [encorelab/ck-board#54]
On laptop trackpads, zoom works by scrolling up/down rather than pinching to zoom in/out

Desired behaviour:

Trackpad
- two-finger scroll up/down/right/left pans across the screen
- pinch for zoom in/out

Mouse wheel
- scroll up/down for zoom in/out
- right-click and mouse move to drag the canvas (regardless of whether in pan mode)

**Comment by JoelWiebe** [comment]
Here is some tentative logic we can use for detecting trackpad vs mouse wheel detection. During a mouse wheel event:
- if deltaY is a whole number or deltaX is not zero, then it is a trackpad
- if deltaY has trailing non-zero decimals points, then it is a mouse wheel

Detecting pinch, during a mouse wheel event:
- if ctrlKey is pressed, then it is a pinch gesture (see details here: https://stackblitz.com/edit/multi-touch-trackpad-gesture)

**Comment by JoelWiebe** [comment]
Hey @StevenWuzz, did you have a chance to look at this? I think I may have found a workaround for identifying trackpad vs mouse wheel. If so, would this be easy to implement?

**Comment by StevenWuzz** [comment]
@JoelWiebe Hi, Joel! Actually, the gesture event technique seems to work only on macOS/iOS devices (https://developer.apple.com/documentation/webkitjs/gestureevent). Furthermore, they are also categorized as non-standard feature (https://developer.mozilla.org/en-US/docs/Web/API/Element/gesturestart_event). Do you still want to proceed with this method?

**Comment by JoelWiebe** [comment]
@StevenWuzz I'm still interested in trying the logic outlined above if you're game for that. With only support for Apple products and the Safari browser I get the sense that it isn't worth investing that one-off solution you linked to for such a specific context.

As a first pass, could we try the logic outlined above (with whole number as a trackpad scroll)? Also had you read that most browsers interpret a trackpad pinch as a scroll event with the ctrl key being pressed, as shown here: https://stackblitz.com/edit/multi-touch-trackpad-gesture ?
