### ISSUE TITLE
Reorganize CK Menu items

### ISSUE THREAD

**Issue by JoelWiebe** [encorelab/ck-board#559]
### Description
Different menu items are available from different contexts, this requires some reorganization for consistency of experience across menu contexts, also a few more menu items should be added back to the nav bar for quick access

**Tasks**

[TODO]

**Comment by LunarFang416** [comment]
@JoelWiebe Since we added the navbar in the CK-Buckets PR, do we still need to reorganize the CK Menu? If not I can close this issue.

**Comment by JoelWiebe** [comment]
@LunarFang416 Good catch, let's close this.
