### ISSUE TITLE
Create Zoom Depth tool

### ISSUE THREAD

**Issue by JoelWiebe** [encorelab/ck-board#58]
In bottom right corner of canvas, display the zoom depth and perhaps provide clickable options to zoom in/out or return to 100% zoom

**Comment by StevenWuzz** [comment]
@JoelWiebe could you elaborate on what you mean by canvas?

**Comment by StevenWuzz** [comment]
@JoelWiebe do you want to current zoom percentage (100%, 75%, etc) to be displayed as well?
