### ISSUE TITLE
Create theme colours and styles

### ISSUE THREAD

**Issue by JoelWiebe** [encorelab/ck-board#59]
Style the application to use Encore blue (Hex 064364) and the Encore logo throughout. 

For example, on the login page
- place a large copy of the Encore logo
![encore-web-logo-colour (1)](https://user-images.githubusercontent.com/6416247/148138658-ad7c99e7-5ed3-461a-af6e-329ad58aaf48.png)
(Encore logo alternative in white below -- please download to view)
![Encore-lab-white-4x](https://user-images.githubusercontent.com/6416247/148138654-a0e8c181-36ef-41d8-97d3-3fab25ac186a.png)

Once logged in
- a small version of the Encore logo on the left side of the top navigation bar 
- colour the navigation bar Encore blue
(Small logo in white below -- please download to view)
![encore-website-sm-logo (1)](https://user-images.githubusercontent.com/6416247/148138645-7e95d53b-f475-4b69-bce1-9130ac505732.png)

For the canvas 
- white for the canvas and 
- light grey (e.g., #F8F8F8) for the background outside of the canvas

These are just some ideas -- feel free to explore your creative expression!

**Comment by Ammar-T** [comment]
Might be worth it to create a "universal theme" with material-ui to create a more reusable design. More details can be viewed here: https://material.angular.io/guide/theming

Although, this may not be a good first issue anymore.

**Comment by JoelWiebe** [comment]
@Ammar-T, that's a great idea. This would allow us to create a custom palette, correct? Maybe in the future we could create light- and dark-mode. But this does suddenly sound like a bigger task. We should also think about allowing the teacher to change the background colour ... maybe that fits into this discussion.

**Comment by JoelWiebe** [comment]
Set background canvas colour to a light shade of grey, e.g.: #F8F8F8
