### ISSUE TITLE
Minimize/expand long posts

### ISSUE THREAD

**Issue by Ammar-T** [encorelab/ck-board#7]
If the amount of text in a post surpasses x length, then it should be able to be minimized via a small arrow button on top of the post.

The arrow button should also be able to expand the post again as well.

**Comment by JoelWiebe** [comment]
To reduce clutter on the canvas and for ease of reading, I would recommend not having an expandable note but rather click on the notes for a pop-up, modal dialogue (like Trello) to view the full contents of the note.

**Comment by JoelWiebe** [comment]
For the canvas on the card, set length limits for both the title and the body of text -- but display in full in pop-up modal dialogue.
