### ISSUE TITLE
Additional Pan Controls

### ISSUE THREAD

**Issue by JoelWiebe** [encorelab/ck-board#92]
Can we add additional pan controls to make it easier to navigate a canvas (i.e., using arrow keys to pan up/down and right/left)? 

Also, is it difficulty to have separate touch events for trackpads vs mouse (i.e., using two finger swipe on a trackpad to move up/down and right/left)?

**Comment by StevenWuzz** [comment]
@JoelWiebe Regarding the second task, do you wish to pan up/down/left/right whenever a user swipe the trackpad using two fingers?

**Comment by JoelWiebe** [comment]
@StevenWuzz Do you mind making a couple small changes before closing this?
- increasing the pan rate from 10 to 30 in all directions
- invert up/down so that up arrow moves toward the top of the canvas
- pan with arrow keys always (not just when in pan mode)
